ALTER DATABASE CrudApi COLLATE Latin1_General_CI_AS
GO
CREATE SCHEMA [User]
GO
CREATE TABLE [User].[Users]
(
    [Id] UNIQUEIDENTIFIER PRIMARY KEY,
    [FullName] NVARCHAR(200) NOT NULL,
    [Email] NVARCHAR(50) NOT NULL
)